using System.Collections;
using TMPro;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    public TextMeshProUGUI text;
    public GameObject readyPanel;
    public GameObject ready;
    
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        StartCoroutine(GameSet());
    }

    private IEnumerator GameSet()
    {
        yield return new WaitForSeconds(3f);
        text.text = "3";
        yield return new WaitForSeconds(1f);
        text.text = "2";
        yield return new WaitForSeconds(1f);
        text.text = "1";
        yield return new WaitForSeconds(1f);
        text.text = "GO!";
        readyPanel.SetActive(false);
        yield return new WaitForSeconds(3f);
        ready.SetActive(false);
    }
}
